// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package llmmcp

type ToolExtension struct {
	// The name of the tool
	Name string `json:"name"`

	// Go template for the description, the original description will
	// automatically be rendered into {{ .Description }}.
	DescriptionTemplate string `json:"description_template,omitempty"`
}

type TransportType string

type TransportSSE struct {
	// The endpoint of the mcp server
	Endpoint string `json:"endpoint"`

	// The headers of the request
	Headers map[string]string `json:"headers,omitempty"`
}

type TransportStreamableHTTP struct {
	// The endpoint of the mcp server
	Endpoint string `json:"endpoint"`

	// The headers of the request
	Headers map[string]string `json:"headers,omitempty"`
}

type ConfigTransport struct {
	// The type of the transport
	Type TransportType `json:"type"`

	// The config of the transport
	Config any `json:"config"`
}

type ConfigMCP struct {
	// The transport type of the mcp server
	Transport ConfigTransport `json:"transport"`

	// A list of allowed tools, if empty, all tools except the forbidden
	// are allowed. If enabled_tools and ddisabled_tools overlapped, the
	// overlapped tools are disabled.
	EnabledTools []string `json:"enabled_tools"`

	// A list of forbidden tools, if empty, refer to the logic of enabled.
	DisabledTools []string `json:"disabled_tools"`

	// A list of tool extensions
	ToolExtensions []ToolExtension `json:"tool_extensions"`
}
