// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package larktool

type ToolCreateMessageReply struct {
}

type ToolCreateMessageSend struct {
}

type ToolListMessagesChat struct {
	// start time to search history, specify it only when needed
	StartTime *string `json:"start_time,omitempty"`

	// end time to search history, specify it only when needed
	EndTime *string `json:"end_time,omitempty"`
}

type ToolListMessagesThread struct {
}
