// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package llmskill

type ToolSkillsList struct {
	// Optional category filter (e.g., "mlops")
	Category string `json:"category,omitempty"`

	// Optional task identifier used to probe the active backend
	TaskID string `json:"task_id,omitempty"`
}

type ToolSkillView struct {
	// Name or path of the skill (e.g., "axolotl" or "03-fine-tuning/axolotl").
	// Qualified names like "plugin:skill" resolve to plugin-provided skills.
	Name string `json:"name"`

	// Optional path to a specific file within the skill (e.g., "references/api.md")
	FilePath string `json:"file_path,omitempty"`

	// Optional task identifier used to probe the active backend
	TaskID string `json:"task_id,omitempty"`

	// Apply configured SKILL.md template and inline shell rendering to
	// main skill content. Internal slash/preload callers disable this
	// because they render the skill message themselves.
	Preprocess bool `json:"preprocess"`
}
