// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package larksvc

type Config struct {
	Storage struct {
		Folder string `json:"folder"`
	} `json:"storage"`

	Model struct {
		Name string `json:"name"`

		McpServers []struct {
			Endpoint string `json:"endpoint"`

			Headers map[string]string `json:"headers"`
		} `json:"mcpservers"`
	} `json:"model"`
}
