// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package larksvc

import (
	"github.com/humbornjo/bob/package/llm"
	"github.com/humbornjo/bob/package/llm/mcp"
)

type Config struct {
	Storage struct {
		Folder string `json:"folder"`
	} `json:"storage"`

	Model struct {
		Provider llm.Provider `json:"provider"`

		Name string `json:"name"`

		McpServers []llmmcp.ConfigMCP `json:"mcpservers"`
	} `json:"model"`
}
