// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package config

type Config struct {
	Env string `json:"env"`

	Level string `json:"level"`

	Port string `json:"port"`

	Volcengine struct {
		Tos struct {
			Endpoint string `json:"endpoint"`

			Region string `json:"region"`

			Bucket string `json:"bucket"`

			AccessKey string `json:"access_key"`

			SecretKey string `json:"secret_key"`
		} `json:"tos"`
	} `json:"volcengine"`
}
